services:
  - type: web
    name: mqtt-service
    env: docker
    plan: free
    autoDeploy: true

    ports:
      - port: 1883   # MQTT public port
        protocol: tcp
      - port: 10000  # Render-required HTTP port
        protocol: tcp

    healthCheckPath: /
