services:
  - type: web
    name: mosquitto-broker
    env: docker
    plan: free
    autoDeploy: true

    # Expose MQTT port publicly
    ports:
      - port: 1883
        protocol: tcp
      - port: 8080
        protocol: tcp

    healthCheckPath: /
    healthCheckPort: 8080
