services:
  - type: web
    name: mqtt-service
    env: docker
    plan: free
    autoDeploy: true

    ports:
      - port: 1883
        protocol: tcp
      - port: 8080
        protocol: tcp

    healthCheckPath: /
    healthCheckPort: 8080
